### ISSUE TITLE
Always display photo returned by API

### ISSUE THREAD

**Issue by macklinu** [selfconference/selfconf-android#13]
A change introduced in selfconference/selfconf@cec25ae now returns a robot image if the speaker does not have an image associated with them.

We can now remove the `TextDrawable` library and just always used the photo value from this API call.

Possible placeholder images:

![](https://s3.amazonaws.com/selfconf/robit-1.png)
![](https://s3.amazonaws.com/selfconf/robit-2.png)
![](https://s3.amazonaws.com/selfconf/robit-3.png)
![](https://s3.amazonaws.com/selfconf/robit-4.png)
![](https://s3.amazonaws.com/selfconf/robit-5.png)
![](https://s3.amazonaws.com/selfconf/robit-6.png)

**Comment by crebma** [comment]
Fixed! The website and ios app will also get the same placeholder apps :D
