### ISSUE TITLE
Make a speaker activity

### ISSUE THREAD

**Issue by crebma** [selfconference/selfconf-android#14]
Perhaps we should make a speaker activity that will show the speaker details first and then a list of their talks? That might fix #12

**Comment by macklinu** [comment]
Yeah, good question. Is there enough information associated with a speaker to dedicate a whole screen to them?

**Comment by crebma** [comment]
Sure, same amount as about a session I think.

**Comment by macklinu** [comment]
We omitted the speaker list from the 2016; I'm curious to get feedback at the conference and see if users would like to have a more dedicated way to view speaker information.

Closing for now - will make a new issue if something actionable comes from 2016 conference feedback.
